/* wxedid_rcd_scope.h
   Generated by rcd_autogen v4.0 (mode=full) for the wxedid core library.
   Regenerate: rcd_autogen --base-name=wxedid ... (see rcode/README_rcd_autogen)
   IMPORTANT: rcd_autogen currently fails on bash >= 5.1 (two bugs patched in
   rcode/rcd_autogen.gen: `if [ 0 == fcnt ]` string comparisons, and
   out_dir/root_dir handling in F_GEN_SOURCE when invoked from parent dir).
*/

#ifndef wxedid_RCD_SCP_H
#define wxedid_RCD_SCP_H 1
#include "rcode/rcode.h"
#include "rcode/rcd_alias.h"
#define wxedid_RCD_AUTOGEN_MODE 2
#include <sys/cdefs.h>
__BEGIN_DECLS

struct rcd_scope*
wxedid_rcdGetScopePtr(void) __attribute__((pure));

uint32_t
wxedid_rcdGetStackSize(void) __attribute__((const));

void
wxedid_rcdSetSubScopePtr(struct rcd_scope* scp);

void
wxedid_rcdResetStack(void);

rcode
wxedid_rcdGetStatus(void);

void
wxedid_rcdPushRcode(rcode retU);

int
wxedid_rcdGetCallStack(struct rcd_scope* scp, char* buf, int bsz)
__nonnull((2));

int
wxedid_rcdGetMsg(struct rcd_scope* scp, rcode retU, char* buf, int bsz)
__nonnull((3));

int
wxedid_rcdGetMinMsgBufSz(struct rcd_scope* scp);

void
wxedid_rcdSetMsg(rcode rcd, const char* fmt, ...)
__attribute__(( format(printf, 2, 3) ));

/* push fault + return */
#define wxedid_RCD_PUSH_RETURN(_rcd) \
	{ \
		wxedid_rcdPushRcode(_rcd); \
		return (_rcd); \
	}

/* set & push fault */
#define wxedid_RCD_SET_PUSH_FAULT(_rcd) \
	{ \
		RCD_SET_FAULT(_rcd); \
		wxedid_rcdPushRcode(_rcd); \
	}

/* set & push fault + return */
#define wxedid_RCD_SET_PUSH_FAULT_RETURN(_rcd) \
	{ wxedid_RCD_SET_PUSH_FAULT(_rcd); return (_rcd); }

/* set & push fault MSG */
#define wxedid_RCD_SET_PUSH_FAULT_MSG(_rcd, _msg) \
	{ \
		RCD_SET_FAULT_MSG(_rcd, _msg); \
		wxedid_rcdPushRcode(_rcd); \
	}

/* set & push fault MSG + return */
#define wxedid_RCD_SET_PUSH_FAULT_MSG_RETURN(_rcd, _msg) \
	{ wxedid_RCD_SET_PUSH_FAULT_MSG(_rcd, _msg); return (_rcd); }

/* set fault VMSG (volatile message)
	NOTE: changing the rcode before returning invalidates the message. */
#define wxedid_RCD_SET_FAULT_VMSG( _rcd, _fmt, ... ) \
	{ \
		_rcd = RCD_SET_VAL( RCD_UNIT, __LINE__, RCD_FVMSG ); \
		wxedid_rcdSetMsg(_rcd, _fmt, ##__VA_ARGS__); \
	}

/* set & push fault VMSG */
#define wxedid_RCD_SET_PUSH_FAULT_VMSG(_rcd, _fmt, ...) \
	{ \
		wxedid_RCD_SET_FAULT_VMSG(_rcd, _fmt, ##__VA_ARGS__) \
		wxedid_rcdPushRcode(_rcd); \
	}

/* set fault VMSG + return */
#define wxedid_RCD_RETURN_FAULT_VMSG( _rcd, _fmt, ... ) \
	{ \
		wxedid_RCD_SET_FAULT_VMSG(_rcd, _fmt, ##__VA_ARGS__) \
		return (_rcd); \
	}

/* set & push fault VMSG + return */
#define wxedid_RCD_SET_PUSH_FAULT_VMSG_RETURN( _rcd, _fmt, ... ) \
	{ \
		wxedid_RCD_SET_PUSH_FAULT_VMSG(_rcd, _fmt, ##__VA_ARGS__); \
		return (_rcd); \
	}

/* get message associated with rcode */
#define wxedid_RCD_GET_MSG(_rcd, _buf, _bsz) \
	wxedid_rcdGetMsg(wxedid_rcdGetScopePtr(), (_rcd), (_buf), (_bsz))

/* get Call Stack for *this* scope */
#define wxedid_RCD_GET_CALL_STACK(_buf, _bsz) \
	wxedid_rcdGetCallStack( wxedid_rcdGetScopePtr(), (_buf), (_bsz) )

/* TRUE/FALSE variants used by the core */
#define wxedid_RCD_RETURN_TRUE_MSG( _rcd, _msg ) \
	{ \
		RCD_SET_TRUE(_rcd); \
		wxedid_RCD_SET_PUSH_FAULT_MSG(_rcd, _msg); \
		return (_rcd); \
	}

#define wxedid_RCD_RETURN_FALSE_MSG( _rcd, _msg ) \
	{ \
		RCD_SET_FALSE(_rcd); \
		wxedid_RCD_SET_PUSH_FAULT_MSG(_rcd, _msg); \
		return (_rcd); \
	}

__END_DECLS
#endif /* wxedid_RCD_SCP_H */
